### ISSUE TITLE
Lab5 Roadmap

### ISSUE THREAD

**Issue by Ale142** [Ale142/group03-reactive-kafka#1]
**TicketCatalogueService**: is in charge of managing the sales process.
Endpoints:
- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8

**PaymentService**:  is in charge of sending payment information to the bank through Kafka Topic.
Endpoints:
- [x] #9
- [x] #10

**Those microservices must be reactive**

[Hint](https://dev.to/magnuspedro/setting-up-spring-kafka-with-kotlin-53ea) for setupping Kafka in Spring

**Comment by fxbrit** [comment]
all done, having dinner now:

<img src="https://user-images.githubusercontent.com/34379516/170714750-9f03d7f7-0139-4035-bcd7-a8a320725bf1.png" width="400">
